[package]
name = "iris_analysis"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
plotters = "0.3.0"

[lib]
name = "iris_functions"
path = "src/lib.rs"
